html:

# Styling options for the HTML report
    style:
        full_width: yes
        theme: flatly
        primary_color: '#00B0F5'
# Minify the html
    minify_html: yes

# Offline support
    use_local_assets: yes
# Title of the document
title: Claimstar Profiling Report

# Number of workers (0=multiprocessing.cpu_count())
pool_size: 8

# Per variable type description settings
vars:
    num:
        quantiles:
        - 0.05
        - 0.25
        - 0.5
        - 0.75
        - 0.95
        skewness_threshold: 20
        low_categorical_threshold: 5
    cat:
        check_composition: no
        cardinality_threshold: 50
        n_obs: 5
    bool:
        n_obs: 3

# Sort the variables. Possible values: ascending, descending or None (leaves original sorting)
sort: None

# which diagrams to show
missing_diagrams:
    bar: yes
    matrix: yes
    heatmap: true
    dendrogram: true

correlations:
    pearson:
        calculate: yes
        warn_high_correlations: yes
        threshold: 0.9
    spearman:
        calculate: yes
        warn_high_correlations: no
    kendall:
        calculate: yes
        warn_high_correlations: no
    phi_k:
        calculate: no
        warn_high_correlations: no
    cramers:
        calculate: no
        warn_high_correlations: yes
        threshold: 0.9
    recoded:
        calculate: yes
        warn_high_correlations: yes
        threshold: 1.0

# For categorical
categorical_maximum_correlation_distinct: 100

# Plot-specific settings
plot:
# Image format (svg or png)
    image_format: svg
    dpi: 600

    correlation:
        cmap: bwr

    missing:
        cmap: RdBu
# Force labels when there are > 50 variables
# https://github.com/ResidentMario/missingno/issues/93#issuecomment-513322615
        force_labels: yes

    histogram:
# is used for numeric variables
        bayesian_blocks_bins: yes

# If 'bayesian_blocks_bins' fails to provide a valid number of bins.
        bins: 50
# Also used for equal size histogram

# The number of observations to show
n_obs_unique: 5
n_extreme_obs: 5
n_freq_table_max: 10

samples:
    head: 10
    tail: 10

# When in a Jupyter notebook
notebook:
    iframe:
        height: 1000px
        width: 100%
# or 'src'
        attribute: srcdoc
